# Path to your oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="steeef"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

ZSH_TMUX_FIXTERM=true

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(tmux git virtualenv virtualenvwrapper iseage zsh-syntax-highlighting zsh-autosuggestions)

capability() {
    grep $1 ~/.capabilities
}

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"

source $ZSH/oh-my-zsh.sh

export EDITOR='vim'

if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.npm-global/bin" ]; then
    PATH="$HOME/.npm-global/bin:$PATH"
fi

if [[ "$TERM" == "xterm-termite" ]]; then
    export TERM="xterm"
fi

#export TERM="xterm-256color"

#alias tmux="tmux -2"

export MTR_OPTIONS=-t

if [ -f "$HOME/.dircolors" ]; then
    eval `dircolors $HOME/.dircolors`
fi

if [ -d "$HOME/projects/go" ]; then
    export GOPATH="$HOME/projects/go"
    export PATH="$GOPATH/bin:$PATH"
fi

if [ -n "$TMUX" ]; then
    export TERM="screen-256color"
fi

export GPG_TTY=$(tty)
if [[ -n "$SSH_CONNECTION" ]] ;then
    export PINENTRY_USER_DATA="USE_CURSES=1"
fi

if [[ -n "$VIRTUAL_ENV" ]]; then
    source $VIRTUAL_ENV/bin/activate
fi

if [[ -d "$HOME/.local/bin" ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

ansiblerole() {
    mkdir -p roles/$1/{defaults,files,handlers,meta,tasks,templates,vars}
}

export ANSIBLE_NOCOWS=1

if capability touchpad; then
    synclient TapButton3=2 TapButton2=3 TapButton1=0
fi

if [ -d "/opt/metasploit-framework/bin" ]; then
    export PATH="/opt/metasploit-framework/bin:$PATH"
fi

if [ -d $HOME/.rvm/bin ]; then
    # Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
    export PATH="$PATH:$HOME/.rvm/bin"
fi

# Some systems have rbenv instead of rvm
if [ -d $HOME/.rbenv/bin ]; then
    export PATH="$PATH:$HOME/.rbenv/bin"
fi

if [ -d $HOME/.pyenv ]; then
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

python3 -c 'import ara' > /dev/null 2>&1
if [[ "$?" -eq "0" ]]; then
    export ANSIBLE_CALLBACK_PrailsLUGINS="$(python3 -c 'import os,ara; print(os.path.dirname(ara.__file__))')/plugins/callbacks"
fi

export DOTNET_CLI_TELEMETRY_OPTOUT=1

alias dnsdeploy='cd ~/dns; ansible-playbook -i hosts playbook.yml --ask-become-pass; cd -'

fbr() {
    local branches branch
    branches=$(git branch --all | grep -v HEAD) &&
    branch=$(echo "$branches" | fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&
    git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /home/matt2/bin/vault vault
bindkey '^ ' autosuggest-accept

PATH="/home/mattg/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/mattg/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/mattg/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/mattg/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/mattg/perl5"; export PERL_MM_OPT;

if [ -d $HOME/.cargo ]; then
    export PATH=$HOME/.cargo/bin:$PATH
fi
